[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

## Populate Seal Ability Table
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if (self.ability.set == 'Voucher' or self.config.center.demo) and (self.ability.name ~= 'Antimatter' or not (self.config.center.discovered or self.bypass_discovery_center)) then'''
position = 'before'
match_indent = true
payload = '''
if self.ability.set == 'Mythos' then
    self.children.center:draw_shader('booster', nil, self.ARGS.send_to_shader)
end
'''